"""update

Revision ID: 353be0ca40a1
Revises: e1337c117a51
Create Date: 2026-08-02 05:33:37.238327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '353be0ca40a1'
down_revision: Union[str, Sequence[str], None] = 'e1337c117a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_rooms', sa.Column('subject_class_name', sa.String(length=100), nullable=False))
    op.add_column('class_rooms', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.add_column('class_rooms', sa.Column('semester', sa.Enum('Semester_1', 'Semester_2', 'Semester_3', name='semester'), nullable=False))
    op.add_column('class_rooms', sa.Column('academic_year', sa.String(length=9), nullable=False, comment='VD: 2025-2026'))
    op.add_column('class_rooms', sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'FINISHED', name='classstatus'), nullable=False))
    op.add_column('class_rooms', sa.Column('max_students', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_class_identity', 'class_rooms', ['subject_id', 'subject_class_name', 'semester', 'academic_year'])
    op.create_foreign_key('fk_class_rooms_subject_id', 'class_rooms', 'subjects', ['subject_id'], ['id'])
    op.add_column('exam', sa.Column('subject_class_id', sa.Integer(), nullable=False))
    op.add_column('exam', sa.Column('room_id', sa.Integer(), nullable=False))
    op.add_column('exam', sa.Column('exam_date', sa.DateTime(), nullable=False))
    op.add_column('exam', sa.Column('type', sa.Enum('MIDTERM', 'FINALTEST', name='typeofexam'), nullable=False))
    op.add_column('exam', sa.Column('time_frame', sa.Enum('SHIFT_1', 'SHIFT_2', 'SHIFT_3', 'SHIFT_4', 'SHIFT_5', name='timeframe'), nullable=False))
    op.add_column('exam', sa.Column('semester', sa.Enum('Semester_1', 'Semester_2', 'Semester_3', name='semester'), nullable=False))
    op.add_column('exam', sa.Column('duration', sa.Integer(), nullable=False, comment='Time limit in minutes'))
    op.add_column('exam', sa.Column('status', sa.Enum('SCHEDULED', 'FINISHED', 'CANCELLED', name='examstatus'), nullable=False))
    op.create_unique_constraint('uq_room_datetime', 'exam', ['room_id', 'exam_date', 'time_frame'])
    op.create_foreign_key('fk_exam_room_id', 'exam', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key('fk_exam_subject_class_id', 'exam', 'class_rooms', ['subject_class_id'], ['id'])
    op.drop_column('rooms', 'is_available')
    op.add_column('subjects', sa.Column('subject_code', sa.String(length=20), nullable=False, comment='VD: IT001, CTDLGT'))
    op.add_column('subjects', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('subjects', sa.Column('credits', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_subjects_subject_code', 'subjects', ['subject_code'])
    op.add_column('users', sa.Column('user_code', sa.String(length=20), nullable=False, comment='VD: GV001, SV230001'))
    op.create_unique_constraint('uq_users_user_code', 'users', ['user_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_user_code', 'users', type_='unique')
    op.drop_column('users', 'user_code')
    op.drop_constraint('uq_subjects_subject_code', 'subjects', type_='unique')
    op.drop_column('subjects', 'credits')
    op.drop_column('subjects', 'name')
    op.drop_column('subjects', 'subject_code')
    op.add_column('rooms', sa.Column('is_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint('fk_exam_subject_class_id', 'exam', type_='foreignkey')
    op.drop_constraint('fk_exam_room_id', 'exam', type_='foreignkey')
    op.drop_constraint('uq_room_datetime', 'exam', type_='unique')
    op.drop_column('exam', 'status')
    op.drop_column('exam', 'duration')
    op.drop_column('exam', 'semester')
    op.drop_column('exam', 'time_frame')
    op.drop_column('exam', 'type')
    op.drop_column('exam', 'exam_date')
    op.drop_column('exam', 'room_id')
    op.drop_column('exam', 'subject_class_id')
    op.drop_constraint('fk_class_rooms_subject_id', 'class_rooms', type_='foreignkey')
    op.drop_constraint('uq_class_identity', 'class_rooms', type_='unique')
    op.drop_column('class_rooms', 'max_students')
    op.drop_column('class_rooms', 'status')
    op.drop_column('class_rooms', 'academic_year')
    op.drop_column('class_rooms', 'semester')
    op.drop_column('class_rooms', 'subject_id')
    op.drop_column('class_rooms', 'subject_class_name')
    # ### end Alembic commands ###
