"""update databse

Revision ID: 48db766d51ca
Revises: 
Create Date: 2026-08-08 13:46:30.072140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48db766d51ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    op.create_table('subjects',
    sa.Column('subject_code', sa.String(length=20), nullable=False, comment='VD: IT001, CTDLGT'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('subject_code', name=op.f('uq_subjects_subject_code'))
    )
    op.create_table('users',
    sa.Column('user_code', sa.String(length=20), nullable=False, comment='VD: GV001, SV230001'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='userrole'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('user_code', name=op.f('uq_users_user_code'))
    )
    op.create_table('class_rooms',
    sa.Column('subject_class_name', sa.String(length=100), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Enum('Semester_1', 'Semester_2', 'Semester_3', name='semester'), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False, comment='VD: 2025-2026'),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'FINISHED', name='classstatus'), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_class_rooms_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_rooms')),
    sa.UniqueConstraint('subject_id', 'subject_class_name', 'semester', 'academic_year', name='uq_class_identity')
    )
    op.create_table('enrollments',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_class_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Enum('Semester_1', 'Semester_2', 'Semester_3', name='semester'), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True, comment='Điểm tổng kết môn (sau khi có điểm giữa kỳ + cuối kỳ)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_enrollments_student_id_users')),
    sa.ForeignKeyConstraint(['subject_class_id'], ['class_rooms.id'], name=op.f('fk_enrollments_subject_class_id_class_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('student_id', 'subject_class_id', 'semester', name='uq_student_class_semester')
    )
    op.create_table('exam',
    sa.Column('subject_class_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('MIDTERM', 'FINALTEST', name='typeofexam'), nullable=False),
    sa.Column('time_frame', sa.Enum('SHIFT_1', 'SHIFT_2', 'SHIFT_3', 'SHIFT_4', 'SHIFT_5', name='timeframe'), nullable=False),
    sa.Column('semester', sa.Enum('Semester_1', 'Semester_2', 'Semester_3', name='semester'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False, comment='Time limit in minutes'),
    sa.Column('status', sa.Enum('SCHEDULED', 'FINISHED', 'CANCELLED', name='examstatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_exam_room_id_rooms')),
    sa.ForeignKeyConstraint(['subject_class_id'], ['class_rooms.id'], name=op.f('fk_exam_subject_class_id_class_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam')),
    sa.UniqueConstraint('room_id', 'exam_date', 'time_frame', name='uq_room_datetime')
    )
    op.create_table('schedules',
    sa.Column('subject_class_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='weekday'), nullable=False),
    sa.Column('session', sa.Enum('MORNING', 'AFTERNOON', name='session'), nullable=False, comment='Buổi sáng/chiều'),
    sa.Column('semester', sa.Enum('Semester_1', 'Semester_2', 'Semester_3', name='semester'), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_schedules_room_id_rooms')),
    sa.ForeignKeyConstraint(['subject_class_id'], ['class_rooms.id'], name=op.f('fk_schedules_subject_class_id_class_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules')),
    sa.UniqueConstraint('room_id', 'weekday', 'session', 'semester', 'academic_year', name='uq_room_weekday_session')
    )
    op.create_table('teaching_assignments',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_class_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subject_class_id'], ['class_rooms.id'], name=op.f('fk_teaching_assignments_subject_class_id_class_rooms')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_teaching_assignments_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teaching_assignments')),
    sa.UniqueConstraint('teacher_id', 'subject_class_id', name='uq_teacher_class')
    )
    op.create_table('exam_invigilators',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('fk_exam_invigilators_exam_id_exam')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_exam_invigilators_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_invigilators')),
    sa.UniqueConstraint('exam_id', 'teacher_id', name='uq_exam_teacher')
    )
    op.create_table('exam_registrations',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=True, comment='VD: A01, A02'),
    sa.Column('attendance_status', sa.Enum('PRESENT', 'ABSENT', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('fk_exam_registrations_exam_id_exam')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_exam_registrations_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_registrations')),
    sa.UniqueConstraint('exam_id', 'seat_number', name='uq_exam_seat'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_exam_student')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_registrations')
    op.drop_table('exam_invigilators')
    op.drop_table('teaching_assignments')
    op.drop_table('schedules')
    op.drop_table('exam')
    op.drop_table('enrollments')
    op.drop_table('class_rooms')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('rooms')
    # ### end Alembic commands ###
