"""update avatar for User

Revision ID: fada48908c46
Revises: 
Create Date: 2026-08-15 11:25:12.859754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fada48908c46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'users',
        sa.Column(
            'avatar',
            sa.String(length=500),
            nullable=True
        )
    )

    op.execute(
        "UPDATE users SET avatar = 'https://res.cloudinary.com/qrmh4zb7/image/upload/w5wu4duozmvf2klosgld.png' WHERE avatar IS NULL"
    )

    op.alter_column(
        'users',
        'avatar',
        existing_type=sa.String(length=500),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
